사탕을 모두 먹어치우도록 수정 🥐
junhoyeo/honeycomb pull request #2
Opened 2020-06-24 14:20 UTC by electrochemistry04

Junho Yeo, Junho Yeo
The great big greedy nincompoop
Junho Yeo, so big and vile
So greedy, foul, and infantile.
Come on we cried
The time is ripe
To send him shooting up the pipe
But don't dear children be alarmed
Junho Yeo will not be harmed
Junho Yeo will not be harmed

2020-06-24 23:22 UTC, junhoyeo commented on index.ts
> +      console.log(`waiting for..${i}/${timeoutDelayBeforeSubmit}`);
로그 포맷을 더 예쁘게 개선해야 합니다.

2020-06-24 23:23 UTC, junhoyeo commented on index.ts
> +    await page.screenshot({path: 'result.png'});
`{ path: 'result.png' }` 양쪽 중괄호 사이에 공백이 필요합니다.

2020-06-24 23:24 UTC, junhoyeo commented on index.ts
> -  console.log(answers);
프로그램이 동작을 멈추거나 수동으로 입력하길 원하는 경우에 대비하여 정답을 로깅하는 것이 필요합니다.

2020-06-24 23:25 UTC, junhoyeo commented on index.ts
> +    } = uncompletedProblems[i] as IProblem;
가독성 향상을 위해 `Array.prototype.forEach` 메소드를 사용해야 합니다.

2020-06-24 23:28 UTC, junhoyeo commented on credentials.example.json
> +  "targetURL": "http://williwonka.com/chocolate/itemlist",
예시는 하위 엔드포인트가 없는 `rootURL`의 형태로 제공되어야 직관적인 이해가 가능합니다. 실제로도 rootURL을 집어넣지 않으면 로그인 등 다른 페이지 이동이 어려워집니다.
그러니까 `targetURL`보다는 `rootURL`이 더 알맞는 이름이 됩니다(호환성 측면에서도요).

2020-06-24 23:29 UTC, junhoyeo requested changes
You're turning violet, Violet!

2020-06-24 23:30 UTC, junhoyeo commented on index.ts
> +      console.log(`waiting for..${i}/${timeoutDelayBeforeSubmit}`);
제가 프로그래스 바를 넣어볼게요.

2020-06-24 23:35 UTC, electrochemistry04 commented on credentials.example.json
> +  "targetURL": "http://williwonka.com/chocolate/itemlist",
실제로 작업을 수행하는 타겟인 `targetURL`을 참조하도록 변경하였습니다.
기존 코드에서는 타겟이 하드코딩되어있었기 때문에 소스코드를 통해 rootURL을 예측할 수 있다는 문제가 있었습니다.
로그인 페이지로의 이동은 auth를 거치지 않으면 자동으로 리다이렉트 되기 때문에 문제가되지 않습니다.

2020-06-25 02:47 UTC, smsmsmsmin commented
다들 사랑합니둥ㅇ 〰️ 🥰

2020-06-25 03:53 UTC, junhoyeo commented on credentials.example.json
> +  "targetURL": "http://williwonka.com/chocolate/itemlist",
알게씁니댜

2020-06-25 07:43 UTC, junhoyeo commented on index.ts
> +    } = uncompletedProblems[i] as IProblem;
`forEach` 하니까 비동기 문제 때문에 죽어버리길래 걍 `for...of`로 바꿈

2020-06-25 07:43 UTC, merged